### ISSUE TITLE
PowerMeasTest Error

### ISSUE THREAD

**Issue by steve-in** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#141]
Hi

"Configure the **server IP address** and port number to be used for SAS-CBSD messaging.  The IP address should match the IP address of the server on which the test harness is running."

IS the "server IP address" mean  AP IP address or cloud sever on Host PC or harness running PC IP address ?
And AP SAS account URL address is harness running PC IP address?

And How to solve the below error message ?

Granted Spectrum Max Eirp = 13dBm/MHz
The Mock-SAS has been started please enabling CBSD for the power measurement test, the Mock-SAS will keep running during the test
the selected test from the user : PowerMeasTest is starting now

Traceback (most recent call last):
  File "C:\Users\RF\Desktop\Citizens-Broadband-Radio-Service-Device-1.0.0.3\Citizens-Broadband-Radio-Service-Device-1.0.0.3\CBRS_Mock_SAS_Python_Master\cbrsPython-master\cbrsPython\controllers\StartPowerMeas.py", line 239, in <module>
    ctx.load_verify_locations(os.path.normpath(os.path.join(str(dirPath), get_Element_From_Config_File(confFile,"caCerts"))))
IOError: [Errno 2] No such file or directory

**Comment by cwilliams-ericsson** [comment]
Hi,

The server IP address in the config file is intended to be the IP address on the device (host PC or server) on which the Test Harness is running.  It is used by the python code to bind the Test Harness socket to the correct IP address.  As such, that address will be used by the UUT as the IP address of the Test Harness (provided there is no NAT in your setup, which is not recommended!).

As for the error message:   The line in question is attempting to retrieve and load the "caCerts" entry in the config.xml file in the Configuration folder.  So, I would assume either (i) the Configuration folder or config.xml file cannot be found, or (ii) the caCerts entry in the config.xml file either does not exist or the file it points to does not exist or is not a correctly formatted root CA file.

In the config.xml file there is entry:
<caCerts>certificates/rootCA_certificate.pem</caCerts>
which points to the root CA certificate file.  Note that there should not normally be a leading "/" in the path any of the files specified in the config.xml file.

**Comment by cwilliams-ericsson** [comment]
Sorry above config.xml entry should read:
\<caCerts>certificates/rootCA_certificate.pem\</caCerts>

**Comment by steve-in** [comment]
Thank you for answer

and then test hannes has a error. How to solve them?

Traceback (most recent call last):
  File "C:\Users\HCT-RF\Desktop\Citizens-Broadband-Radio-Service-Device-1.0.0.3\Citizens-Broadband-Radio-Service-Device-1.0.0.3\CBRS_Mock_SAS_Python_Master\cbrsPython-master\cbrsPython\controllers\StartPowerMeas.py", line 245, in <module>
    app.run(host_ip,sever_port,threaded=True,request_handler=WSGIRequestHandler,ssl_context=ctx)
  File "C:\Python27\lib\site-packages\flask\app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 739, in run_simple
    inner()
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 699, in inner
    fd=fd)
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 587, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 504, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "C:\Python27\lib\SocketServer.py", line 420, in __init__
    self.server_bind()
  File "C:\Python27\lib\BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "C:\Python27\lib\SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions

**Comment by cwilliams-ericsson** [comment]
I have not seen that problem before, nor seen it reported here.  Based on a bit of googling, I suspect a few possibilities you could explore:
- Firewall limiting access to ip address/port?  Check settings.
- Improper IP address / port number in config.xml file?
- Trying to use a port which is already bound to another process?
- Trying to use a port which you don't have user-privilege access to?

For the last two, ensure you are using a port number > 1024.  Maybe ensure you are using port 5000, as this was default so is what others are using.  If you are already using 5000, try another (i.e. port 5001, 5002, etc.).
