### ISSUE TITLE
StartOfProject error

### ISSUE THREAD

**Issue by yves1988** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#143]
Hi:
   Here I run StartOfProject.py,and can start it.but when I set a file ends with".csv",it came to error.
  How can solve it?

 Traceback (most recent call last):
  File "C:\Python27\Citizens-Broadband-Radio-Service-Device-master\CBRS_Mock_SAS_Python_Master\cbrsPython-master\cbrsPython\controllers\StartOfProject.py", line 146, in <module>
    run_New_Test(dirPath, confFile, loggerHandler)
  File "C:\Python27\Citizens-Broadband-Radio-Service-Device-master\CBRS_Mock_SAS_Python_Master\cbrsPython-master\cbrsPython\controllers\StartOfProject.py", line 75, in run_New_Test
    run_New_Test(dirPath, confFile, loggerHandler)
  File "C:\Python27\Citizens-Broadband-Radio-Service-Device-master\CBRS_Mock_SAS_Python_Master\cbrsPython-master\cbrsPython\controllers\StartOfProject.py", line 75, in run_New_Test
    run_New_Test(dirPath, confFile, loggerHandler)
  File "C:\Python27\Citizens-Broadband-Radio-Service-Device-master\CBRS_Mock_SAS_Python_Master\cbrsPython-master\cbrsPython\controllers\StartOfProject.py", line 100, in run_New_Test
    ctx.load_verify_locations(os.path.normpath(os.path.join(str(dirPath), get_Element_From_Config_File(confFile,"caCerts"))))
IOError: [Errno 2] No such file or directory

**Comment by cwilliams-ericsson** [comment]
It appears you may not have your test certificates set up properly.  Please ensure you have completed the following:
1. Generate test certificates as per readme_file_x509_RSA_certs_test_labs.txt (in cbrsPython-master/certificates/How_To_Generate_Certificates), and copy the final certificates into the cbrsPython-master/certificates directory).
2. Modify the configuration file (conf.xml in cbrsPython-master/Configuration) to point to the correct certificates you created and copied into the certificates folder

**Comment by yves1988** [comment]
> It appears you may not have your test certificates set up properly. Please ensure you have completed the following:
> 
> 1. Generate test certificates as per readme_file_x509_RSA_certs_test_labs.txt (in cbrsPython-master/certificates/How_To_Generate_Certificates), and copy the final certificates into the cbrsPython-master/certificates directory).
> 2. Modify the configuration file (conf.xml in cbrsPython-master/Configuration) to point to the correct certificates you created and copied into the certificates folder


thank you for answer,
and I already put readme_file_x509_RSA_certs_test_labs.txt in the correct path.the error line 75 is missing,and how I need to modify the configuration file,I tried ,but it doesn't work.

**Comment by yves1988** [comment]
> It appears you may not have your test certificates set up properly. Please ensure you have completed the following:
> 
> 1. Generate test certificates as per readme_file_x509_RSA_certs_test_labs.txt (in cbrsPython-master/certificates/How_To_Generate_Certificates), and copy the final certificates into the cbrsPython-master/certificates directory).
> 2. Modify the configuration file (conf.xml in cbrsPython-master/Configuration) to point to the correct certificates you created and copied into the certificates folder

thank you for answer,
and I already put readme_file_x509_RSA_certs_test_labs.txt in the correct path.the error line 75 is missing,and how I need to modify the configuration file,I tried ,but it doesn't work.
