### ISSUE TITLE
Mock-SAS is not starting due to jwt implemetation syntax error

### ISSUE THREAD

**Issue by idanrazisr** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#69]
Taking the latest branch from Ericsson 17-Nov-2017, this branch implemented the CPI signed data encoding/decoding.
For this it is also required to do "pip install jwt" to install the jwt python library - need to update the Mock-SAS tutorial for this.

After jwt installation the Mock-SAS still does not start with the following Syntax Error error:

c:\cbrsPython-master\cbrsPython\controllers>StartOfProject.py
Traceback (most recent call last):
  File "C:\cbrsPython-master\cbrsPython\controllers\StartOfProject.py", line 7, in <module>
    from controllers.CLIHandler import CLIHandler
  File "C:\cbrsPython-master\cbrsPython\controllers\..\controllers\CLIHandler.py", line 11, in <module>
    from model.Engine import MyEngine
  File "C:\cbrsPython-master\cbrsPython\controllers\..\model\Engine.py", line 8, in <module>
    from model.CBRSRequestHandler import CBRSRequestHandler as cbrsObj
  File "C:\cbrsPython-master\cbrsPython\controllers\..\model\CBRSRequestHandler.py", line 16, in <module>
    import jwt
  File "C:\Python27\lib\site-packages\jwt\__init__.py", line 17, in <module>
    from .jwk import (
  File "C:\Python27\lib\site-packages\jwt\jwk.py", line 60
    def is_sign_key(self) -> bool:
                          ^
SyntaxError: invalid syntax

c:\cbrsPython-master\cbrsPython\controllers>

**Comment by cwilliams-ericsson** [comment]
As noted in the latest tutorial document on Kavi, please be sure that you install:
**"pyjwt"** and NOT **"jwt"** .  Unfortunately both packages are similar but not compatible.

**Comment by cwilliams-ericsson** [comment]
you can use pip to uninstall jwt, then install pyjwt.

**Comment by idanrazisr** [comment]
installing pyjwt solved the issue. Closing issue.
